server:
  port: 8888
spring:
  application:
    name: online-shopping-config-server
 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/oengajohn/spring-microservices-config-repository
          default-label: main
          skipSslValidation: true
          force-pull: true
          timeout: 5 #default
          clone-on-start: true
          search-paths: '\{application}'
          deleteUntrackedBranches: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
    fetch-registry: false
    register-with-eureka: false

