### Simple hello endpoint
GET http://localhost:6000/api/hello HTTP/1.1

### List Products
# @name ProductList
GET http://localhost:6000/api/products HTTP/1.1


### Save Product
# @name Saveproduct
POST http://localhost:6000/api/products HTTP/1.1
Content-Type: application/json

{
    "name":"Phone",
    "price":"15799.00",
    "productCode":"PHN001"
}


### Get Product
# @name GetProductById
GET http://localhost:6000/api/products/5 HTTP/1.1


### Place Order
# @name placeorder
POST http://localhost:6001/api/orders/placeOrder HTTP/1.1
Content-Type: application/json

{
   "orderItems":[
        {
            "productCode":"NDIZI_01",
            "quantity":100
        },
        {
            "productCode":"PNP_01",
            "quantity":50
        }
   ]
}


### Save Inventory
# @name SaveInventory
POST http://localhost:6002/api/inventory/create HTTP/1.1
Content-Type: application/json

{
    "productCode":"PIN001",
    "quantity":"5"
}


