server:
  port: 6001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ordersdb
    username: root
    password: generic
  application:
    name: order-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


