server:
  port: 6000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: root
    password: generic
  application:
    name: product-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

